project_name: lakeFS
before:
  hooks:
    - go mod download
    - make gen
release:
  disable: false
  prerelease: true
builds:
- id: lakefs
  main: ./cmd/lakefs
  binary: lakefs
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/treeverse/lakefs/pkg/version.Version={{.Version}}
  goarch:
  - arm64
  goos:
  - darwin
  - linux
- id: lakectl
  main: ./cmd/lakectl
  binary: lakectl
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/treeverse/lakefs/pkg/version.Version={{.Version}}
  goarch:
  - arm64
  goos:
  - darwin
  - linux
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
- format: binary
  id: binary
  name_template: "{{ .Version }}_{{ .Os }}_{{ .Arch }}/lakectl"
  builds:
   - lakectl
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
blobs:
- provider: s3
  region: us-east-1
  bucket: treeverse-clients-us-east
  folder: "lakectl/{{.Version}}"
  ids:
    - binary

