files:
  client.mustache:
    templateType: SupportingFiles
    folder: lakefs_sdk
    destinationFilename: client.py
infoName: Treeverse
infoEmail: services@treeverse.io
packageName: lakefs_sdk
projectName: lakefs-sdk
packageUrl: https://github.com/treeverse/lakeFS/tree/master/clients/python
