name: releaser

on:
  push:
    branches:
      - feature/delta/releaser
  release:
    types: [published]

permissions:
  packages: write
  issues: write
  id-token: write
  contents: write

jobs:
  rust-releaser-mac:
    runs-on: macos-12
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Rust Cache
        id: cache-rust
        uses: Swatinem/rust-cache@v2.2.1
        with:
          workspaces: pkg/plugins/diff/delta_diff_server -> target
#      - name: Cache Rust
#        id: cache-rust
#        uses: actions/cache@v3
#        env:
#          cache-name: cache-rust
#        with:
#          path: |
#            pkg/plugins/diff/delta_diff_server/target/release/deps
#            ~/.cargo/registry
#            ~/.cargo/git
#          key: ${{ matrix.target }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
#          restore-keys: ${{ matrix.target }}-build-${{ env.cache-name }}-
#            ${{ matrix.target }}-build-
#            ${{ matrix.target }}-
      - if: ${{ steps.cache-rust.outputs.cache-hit != 'true' }}
        name: Cat the toml
        continue-on-error: true
        run: |
          echo "A miss. Cargo's deps:\n"
          cat pkg/plugins/diff/delta_diff_server/Cargo.toml
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path pkg/plugins/diff/delta_diff_server/Cargo.toml
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: delta-${{ matrix.target }}
          path: pkg/plugins/diff/delta_diff_server/target/release/delta_diff
          if-no-files-found: error

  rust-releaser-unix:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Rust Cache
        id: cache-rust
        uses: Swatinem/rust-cache@v2.2.1
        with:
          workspaces: pkg/plugins/diff/delta_diff_server -> target
#      - name: Cache Rust
#        id: cache-rust
#        uses: actions/cache@v3
#        env:
#          cache-name: cache-rust
#        with:
#          path: |
#            pkg/plugins/diff/delta_diff_server/target/release/deps
#            ~/.cargo/registry
#            ~/.cargo/git
#          key: ${{ matrix.target }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
#          restore-keys: ${{ matrix.target }}-build-${{ env.cache-name }}-
#            ${{ matrix.target }}-build-
#            ${{ matrix.target }}-
      - if: ${{ steps.cache-rust.outputs.cache-hit != 'true' }}
        name: Cat the toml
        continue-on-error: true
        run: |
          echo "A miss. Cargo's deps:\n"
          cat pkg/plugins/diff/delta_diff_server/Cargo.toml
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path pkg/plugins/diff/delta_diff_server/Cargo.toml
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: delta-${{ matrix.target }}
          path: pkg/plugins/diff/delta_diff_server/target/release/delta_diff
          if-no-files-found: error

  rust-releaser-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Rust Cache
        id: cache-rust
        uses: Swatinem/rust-cache@v2.2.1
        with:
          workspaces: pkg/plugins/diff/delta_diff_server -> target
#      - name: Cache Rust
#        id: cache-rust
#        uses: actions/cache@v3
#        env:
#          cache-name: cache-rust
#        with:
#          path: |
#            pkg/plugins/diff/delta_diff_server/target/release/deps
#            %userprofile%/.cargo/registry
#            %userprofile%/.cargo/git
#          key: ${{ matrix.target }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
#          restore-keys: ${{ matrix.target }}-build-${{ env.cache-name }}-
#            ${{ matrix.target }}-build-
#            ${{ matrix.target }}-
      - if: ${{ steps.cache-rust.outputs.cache-hit != 'true' }}
        name: Cat the toml
        continue-on-error: true
        run: |
          echo "A miss. Cargo's deps:\n"
          cat pkg/plugins/diff/delta_diff_server/Cargo.toml
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path pkg/plugins/diff/delta_diff_server/Cargo.toml
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: delta-${{ matrix.target }}
          path: pkg/plugins/diff/delta_diff_server/target/release/delta_diff.exe
          if-no-files-found: error

  goreleaser:
    runs-on: ubuntu-20.04
    needs: [rust-releaser-windows, rust-releaser-unix, rust-releaser-mac]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        id: download
        with:
          path: delta/artifacts

      - name: Rename artifacts to match goreleaser artifacts
        working-directory: ${{steps.download.outputs.download-path}}
        run: |
          mv delta-aarch64-apple-darwin delta-darwin-arm64
          mv delta-x86_64-apple-darwin delta-darwin-x86_64
          mv delta-aarch64-pc-windows-msvc delta-windows-arm64
          mv delta-x86_64-pc-windows-msvc delta-windows-x86_64
          mv delta-aarch64-unknown-linux-musl delta-linux-arm64
          mv delta-x86_64-unknown-linux-musl delta-linux-x86_64

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{steps.download.outputs.download-path}}

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.1'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DELTA_ARTIFACTS_LOCATION: delta/artifacts

      - name: Copy Dist
        run: |
          ls -R dist
          aws s3 cp --recursive dist "s3://treeverse-jon-storage/goreleaser/${ github.event.head_commit.id }"
#      - name: Make lakectl public
#        run: aws s3 cp --recursive --acl public-read "s3://treeverse-clients-us-east/lakectl/$(echo ${GITHUB_REF##*/} | cut -d. -f1-2)" "s3://treeverse-clients-us-east/lakectl/$(echo ${GITHUB_REF##*/} | cut -d. -f1-2)" --metadata-directive REPLACE
