on:
  push:
  pull_request:
    branches:
      - develop
      - staging

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2.1
        with:
          formula-name: lakefs
          tag-name: v0.86.0
          download-url: https://github.com/treeverse/lakeFS/archive/v0.86.0.tar.gz
          #create-pullrequest: true 
          homebrew-tap: Homebrew/homebrew-core
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_COMMITTER_TOKEN }}